Updated pr-supervisor script to extend timeout to 12h and modified logic to not wait for itself

diff --git a/.github/workflows/pr-supervisor.yaml b/.github/workflows/pr-supervisor.yaml
--- a/.github/workflows/pr-supervisor.yaml
+++ b/.github/workflows/pr-supervisor.yaml
@@ -18,6 +18,7 @@ on:
 jobs:
   yamato-supervisor:
     runs-on: ubuntu-latest
+    timeout-minutes: 720
     steps:
       - name: Checkout repository
         uses: actions/checkout@v4
@@ -25,6 +26,34 @@ jobs:
       - name: Wait and Verify Yamato Job Status
         env:
           GH_TOKEN: ${{ secrets.GH_TOKEN }}
+          PR_NUMBER: ${{ github.event.pull_request.number }}
         run: |
+          set -e
           sleep 30 
-          gh pr checks ${{ github.event.pull_request.number }} --watch --fail-fast --interval 60
+          
+          MAX_ATTEMPTS=$((12*60))
+          INTERVAL=60
+          
+          for ((i=1;i<=MAX_ATTEMPTS;i++)); do
+            echo "Polling PR checks (attempt $i/$MAX_ATTEMPTS)..."
+            # We want to watch for pending checks beside this check
+            checks=$(gh pr checks $PR_NUMBER --json name,state --jq '[ .[] | select(.name != "yamato-supervisor") ]')
+            
+            pending=$(echo "$checks" | jq '[.[] | select(.state == "pending")] | length')
+            skipping=$(echo "$checks" | jq '[.[] | select(.state == "skipping")] | length')
+            failed=$(echo "$checks" | jq '[.[] | select(.state == "fail")] | length')
+          
+            if [[ "$failed" -gt 0 ]]; then
+              echo "A check has failed! Failing fast."
+              exit 1
+            fi
+
+            echo "Pending checks: $pending, Skipping checks: $skipping"
+
+            if [[ "$pending" -eq 0 ]]; then
+              echo "All non-supervisor checks are completed!"
+              exit 0
+            fi
+          
+            sleep $INTERVAL
+          done
